/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseListQuyenResponse,
  ApiResponseMapStringListQuyenResponse
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layDanhSachQuyen = (

 ) => {
      return customAxiosInstance<ApiResponseListQuyenResponse>(
      {url: `/api/quyen`, method: 'GET'
    },
      );
    }
  export const layDanhSachQuyenPhanNhom = (

 ) => {
      return customAxiosInstance<ApiResponseMapStringListQuyenResponse>(
      {url: `/api/quyen/phan-nhom`, method: 'GET'
    },
      );
    }
  export type LayDanhSachQuyenResult = NonNullable<Awaited<ReturnType<typeof layDanhSachQuyen>>>
export type LayDanhSachQuyenPhanNhomResult = NonNullable<Awaited<ReturnType<typeof layDanhSachQuyenPhanNhom>>>
