/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseListSelectOption,
  ApiResponseLoaiTaiSanResponse,
  ApiResponsePageResponseLoaiTaiSanResponse,
  ApiResponseString,
  LayDanhSach16Params,
  LoaiTaiSanRequest,
  TrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId16 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseLoaiTaiSanResponse>(
      {url: `/api/loai-tai-san/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat16 = (
    id: number,
    loaiTaiSanRequest: LoaiTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponseLoaiTaiSanResponse>(
      {url: `/api/loai-tai-san/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: loaiTaiSanRequest
    },
      );
    }
  export const xoaMem16 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/loai-tai-san/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai10 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/loai-tai-san/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach16 = (
    params?: LayDanhSach16Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseLoaiTaiSanResponse>(
      {url: `/api/loai-tai-san`, method: 'GET',
        params
    },
      );
    }
  export const themMoi16 = (
    loaiTaiSanRequest: LoaiTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponseLoaiTaiSanResponse>(
      {url: `/api/loai-tai-san`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loaiTaiSanRequest
    },
      );
    }
  export const laySelectOptions5 = (

 ) => {
      return customAxiosInstance<ApiResponseListSelectOption>(
      {url: `/api/loai-tai-san/select-options`, method: 'GET'
    },
      );
    }
  export type LayTheoId16Result = NonNullable<Awaited<ReturnType<typeof layTheoId16>>>
export type CapNhat16Result = NonNullable<Awaited<ReturnType<typeof capNhat16>>>
export type XoaMem16Result = NonNullable<Awaited<ReturnType<typeof xoaMem16>>>
export type CapNhatTrangThai10Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai10>>>
export type LayDanhSach16Result = NonNullable<Awaited<ReturnType<typeof layDanhSach16>>>
export type ThemMoi16Result = NonNullable<Awaited<ReturnType<typeof themMoi16>>>
export type LaySelectOptions5Result = NonNullable<Awaited<ReturnType<typeof laySelectOptions5>>>
