/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseListVaiTroDropdownResponse,
  ApiResponsePageResponseVaiTroResponse,
  ApiResponseString,
  ApiResponseVaiTroResponse,
  LayDanhSach1Params,
  TrangThaiRequest,
  VaiTroQuyenUpdateRequest,
  VaiTroRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId1 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseVaiTroResponse>(
      {url: `/api/vai-tro/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat1 = (
    id: number,
    vaiTroRequest: VaiTroRequest,
 ) => {
      return customAxiosInstance<ApiResponseVaiTroResponse>(
      {url: `/api/vai-tro/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: vaiTroRequest
    },
      );
    }
  export const xoaMem1 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/vai-tro/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai1 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/vai-tro/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const capNhatQuyen = (
    id: number,
    vaiTroQuyenUpdateRequest: VaiTroQuyenUpdateRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/vai-tro/${id}/quyen`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: vaiTroQuyenUpdateRequest
    },
      );
    }
  export const layDanhSach1 = (
    params?: LayDanhSach1Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseVaiTroResponse>(
      {url: `/api/vai-tro`, method: 'GET',
        params
    },
      );
    }
  export const themMoi1 = (
    vaiTroRequest: VaiTroRequest,
 ) => {
      return customAxiosInstance<ApiResponseVaiTroResponse>(
      {url: `/api/vai-tro`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: vaiTroRequest
    },
      );
    }
  export const layDropdown = (

 ) => {
      return customAxiosInstance<ApiResponseListVaiTroDropdownResponse>(
      {url: `/api/vai-tro/dropdown`, method: 'GET'
    },
      );
    }
  export type LayTheoId1Result = NonNullable<Awaited<ReturnType<typeof layTheoId1>>>
export type CapNhat1Result = NonNullable<Awaited<ReturnType<typeof capNhat1>>>
export type XoaMem1Result = NonNullable<Awaited<ReturnType<typeof xoaMem1>>>
export type CapNhatTrangThai1Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai1>>>
export type CapNhatQuyenResult = NonNullable<Awaited<ReturnType<typeof capNhatQuyen>>>
export type LayDanhSach1Result = NonNullable<Awaited<ReturnType<typeof layDanhSach1>>>
export type ThemMoi1Result = NonNullable<Awaited<ReturnType<typeof themMoi1>>>
export type LayDropdownResult = NonNullable<Awaited<ReturnType<typeof layDropdown>>>
