/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponsePageResponseNhatKyThaoTacHeThongResponse,
  LayDanhSach27Params
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layDanhSach27 = (
    params?: LayDanhSach27Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseNhatKyThaoTacHeThongResponse>(
      {url: `/api/nhat-ky-thao-tac`, method: 'GET',
        params
    },
      );
    }
  export type LayDanhSach27Result = NonNullable<Awaited<ReturnType<typeof layDanhSach27>>>
