/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseKeHoachBaoTriDinhKyResponse,
  ApiResponsePageResponseKeHoachBaoTriDinhKyResponse,
  ApiResponseString,
  KeHoachBaoTriDinhKyRequest,
  LayDanhSach19Params
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId18 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseKeHoachBaoTriDinhKyResponse>(
      {url: `/api/ke-hoach-bao-tri/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat18 = (
    id: number,
    keHoachBaoTriDinhKyRequest: KeHoachBaoTriDinhKyRequest,
 ) => {
      return customAxiosInstance<ApiResponseKeHoachBaoTriDinhKyResponse>(
      {url: `/api/ke-hoach-bao-tri/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: keHoachBaoTriDinhKyRequest
    },
      );
    }
  export const xoaMem18 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/ke-hoach-bao-tri/${id}`, method: 'DELETE'
    },
      );
    }
  export const yeuCauPheDuyet5 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/ke-hoach-bao-tri/${id}/yeu-cau-phe-duyet`, method: 'PUT'
    },
      );
    }
  export const pheDuyet5 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/ke-hoach-bao-tri/${id}/phe-duyet`, method: 'PUT'
    },
      );
    }
  export const layDanhSach19 = (
    params?: LayDanhSach19Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseKeHoachBaoTriDinhKyResponse>(
      {url: `/api/ke-hoach-bao-tri`, method: 'GET',
        params
    },
      );
    }
  export const themMoi19 = (
    keHoachBaoTriDinhKyRequest: KeHoachBaoTriDinhKyRequest,
 ) => {
      return customAxiosInstance<ApiResponseKeHoachBaoTriDinhKyResponse>(
      {url: `/api/ke-hoach-bao-tri`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: keHoachBaoTriDinhKyRequest
    },
      );
    }
  export type LayTheoId18Result = NonNullable<Awaited<ReturnType<typeof layTheoId18>>>
export type CapNhat18Result = NonNullable<Awaited<ReturnType<typeof capNhat18>>>
export type XoaMem18Result = NonNullable<Awaited<ReturnType<typeof xoaMem18>>>
export type YeuCauPheDuyet5Result = NonNullable<Awaited<ReturnType<typeof yeuCauPheDuyet5>>>
export type PheDuyet5Result = NonNullable<Awaited<ReturnType<typeof pheDuyet5>>>
export type LayDanhSach19Result = NonNullable<Awaited<ReturnType<typeof layDanhSach19>>>
export type ThemMoi19Result = NonNullable<Awaited<ReturnType<typeof themMoi19>>>
