/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponsePageResponsePhieuCapPhatTaiSanResponse,
  ApiResponsePhieuCapPhatTaiSanResponse,
  ApiResponseString,
  LayDanhSach13Params,
  PhieuCapPhatTaiSanRequest,
  TuChoiPheDuyet3Params
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId13 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponsePhieuCapPhatTaiSanResponse>(
      {url: `/api/phieu-cap-phat/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat13 = (
    id: number,
    phieuCapPhatTaiSanRequest: PhieuCapPhatTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuCapPhatTaiSanResponse>(
      {url: `/api/phieu-cap-phat/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: phieuCapPhatTaiSanRequest
    },
      );
    }
  export const xoaMem13 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-cap-phat/${id}`, method: 'DELETE'
    },
      );
    }
  export const yeuCauPheDuyet4 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-cap-phat/${id}/yeu-cau-phe-duyet`, method: 'PUT'
    },
      );
    }
  export const tuChoiPheDuyet3 = (
    id: number,
    params: TuChoiPheDuyet3Params,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-cap-phat/${id}/tu-choi`, method: 'PUT',
        params
    },
      );
    }
  export const pheDuyet4 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-cap-phat/${id}/phe-duyet`, method: 'PUT'
    },
      );
    }
  export const hoanThanh3 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-cap-phat/${id}/hoan-thanh`, method: 'PUT'
    },
      );
    }
  export const layDanhSach13 = (
    params?: LayDanhSach13Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponsePhieuCapPhatTaiSanResponse>(
      {url: `/api/phieu-cap-phat`, method: 'GET',
        params
    },
      );
    }
  export const themMoi13 = (
    phieuCapPhatTaiSanRequest: PhieuCapPhatTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuCapPhatTaiSanResponse>(
      {url: `/api/phieu-cap-phat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: phieuCapPhatTaiSanRequest
    },
      );
    }
  export type LayTheoId13Result = NonNullable<Awaited<ReturnType<typeof layTheoId13>>>
export type CapNhat13Result = NonNullable<Awaited<ReturnType<typeof capNhat13>>>
export type XoaMem13Result = NonNullable<Awaited<ReturnType<typeof xoaMem13>>>
export type YeuCauPheDuyet4Result = NonNullable<Awaited<ReturnType<typeof yeuCauPheDuyet4>>>
export type TuChoiPheDuyet3Result = NonNullable<Awaited<ReturnType<typeof tuChoiPheDuyet3>>>
export type PheDuyet4Result = NonNullable<Awaited<ReturnType<typeof pheDuyet4>>>
export type HoanThanh3Result = NonNullable<Awaited<ReturnType<typeof hoanThanh3>>>
export type LayDanhSach13Result = NonNullable<Awaited<ReturnType<typeof layDanhSach13>>>
export type ThemMoi13Result = NonNullable<Awaited<ReturnType<typeof themMoi13>>>
