/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseHangSanXuatResponse,
  ApiResponseListSelectOption,
  ApiResponsePageResponseHangSanXuatResponse,
  ApiResponseString,
  HangSanXuatRequest,
  LayDanhSach20Params,
  LaySelectOptions9Params,
  TrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId19 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseHangSanXuatResponse>(
      {url: `/api/hang-san-xuat/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat19 = (
    id: number,
    hangSanXuatRequest: HangSanXuatRequest,
 ) => {
      return customAxiosInstance<ApiResponseHangSanXuatResponse>(
      {url: `/api/hang-san-xuat/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: hangSanXuatRequest
    },
      );
    }
  export const xoaMem19 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/hang-san-xuat/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai12 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/hang-san-xuat/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach20 = (
    params?: LayDanhSach20Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseHangSanXuatResponse>(
      {url: `/api/hang-san-xuat`, method: 'GET',
        params
    },
      );
    }
  export const themMoi20 = (
    hangSanXuatRequest: HangSanXuatRequest,
 ) => {
      return customAxiosInstance<ApiResponseHangSanXuatResponse>(
      {url: `/api/hang-san-xuat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hangSanXuatRequest
    },
      );
    }
  export const laySelectOptions9 = (
    params?: LaySelectOptions9Params,
 ) => {
      return customAxiosInstance<ApiResponseListSelectOption>(
      {url: `/api/hang-san-xuat/select-options`, method: 'GET',
        params
    },
      );
    }
  export type LayTheoId19Result = NonNullable<Awaited<ReturnType<typeof layTheoId19>>>
export type CapNhat19Result = NonNullable<Awaited<ReturnType<typeof capNhat19>>>
export type XoaMem19Result = NonNullable<Awaited<ReturnType<typeof xoaMem19>>>
export type CapNhatTrangThai12Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai12>>>
export type LayDanhSach20Result = NonNullable<Awaited<ReturnType<typeof layDanhSach20>>>
export type ThemMoi20Result = NonNullable<Awaited<ReturnType<typeof themMoi20>>>
export type LaySelectOptions9Result = NonNullable<Awaited<ReturnType<typeof laySelectOptions9>>>
