/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponsePageResponsePhieuSuaChuaBaoTriResponse,
  ApiResponsePhieuSuaChuaBaoTriResponse,
  ApiResponseString,
  LayDanhSach9Params,
  PhieuSuaChuaBaoTriRequest,
  TienDoBaoTriChiTietRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId9 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponsePhieuSuaChuaBaoTriResponse>(
      {url: `/api/phieu-sua-chua-bao-tri/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat9 = (
    id: number,
    phieuSuaChuaBaoTriRequest: PhieuSuaChuaBaoTriRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuSuaChuaBaoTriResponse>(
      {url: `/api/phieu-sua-chua-bao-tri/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: phieuSuaChuaBaoTriRequest
    },
      );
    }
  export const xoaMem9 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-sua-chua-bao-tri/${id}`, method: 'DELETE'
    },
      );
    }
  export const yeuCauPheDuyet2 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-sua-chua-bao-tri/${id}/yeu-cau-phe-duyet`, method: 'PUT'
    },
      );
    }
  export const pheDuyet2 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-sua-chua-bao-tri/${id}/phe-duyet`, method: 'PUT'
    },
      );
    }
  export const capNhatTienDoThucHien = (
    id: number,
    tienDoBaoTriChiTietRequest: TienDoBaoTriChiTietRequest[],
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-sua-chua-bao-tri/${id}/cap-nhat-tien-do`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: tienDoBaoTriChiTietRequest
    },
      );
    }
  export const layDanhSach9 = (
    params?: LayDanhSach9Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponsePhieuSuaChuaBaoTriResponse>(
      {url: `/api/phieu-sua-chua-bao-tri`, method: 'GET',
        params
    },
      );
    }
  export const themMoi9 = (
    phieuSuaChuaBaoTriRequest: PhieuSuaChuaBaoTriRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuSuaChuaBaoTriResponse>(
      {url: `/api/phieu-sua-chua-bao-tri`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: phieuSuaChuaBaoTriRequest
    },
      );
    }
  export type LayTheoId9Result = NonNullable<Awaited<ReturnType<typeof layTheoId9>>>
export type CapNhat9Result = NonNullable<Awaited<ReturnType<typeof capNhat9>>>
export type XoaMem9Result = NonNullable<Awaited<ReturnType<typeof xoaMem9>>>
export type YeuCauPheDuyet2Result = NonNullable<Awaited<ReturnType<typeof yeuCauPheDuyet2>>>
export type PheDuyet2Result = NonNullable<Awaited<ReturnType<typeof pheDuyet2>>>
export type CapNhatTienDoThucHienResult = NonNullable<Awaited<ReturnType<typeof capNhatTienDoThucHien>>>
export type LayDanhSach9Result = NonNullable<Awaited<ReturnType<typeof layDanhSach9>>>
export type ThemMoi9Result = NonNullable<Awaited<ReturnType<typeof themMoi9>>>
