/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseCauHinhDonViResponse,
  ApiResponseListCauHinhDonViResponse,
  ApiResponsePageResponseCauHinhDonViResponse,
  ApiResponseString,
  CauHinhDonViRequest,
  LayDanhSach26Params
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId26 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseCauHinhDonViResponse>(
      {url: `/api/cau-hinh-don-vi/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat25 = (
    id: number,
    cauHinhDonViRequest: CauHinhDonViRequest,
 ) => {
      return customAxiosInstance<ApiResponseCauHinhDonViResponse>(
      {url: `/api/cau-hinh-don-vi/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: cauHinhDonViRequest
    },
      );
    }
  export const xoaMem26 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/cau-hinh-don-vi/${id}`, method: 'DELETE'
    },
      );
    }
  export const layDanhSach26 = (
    params?: LayDanhSach26Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseCauHinhDonViResponse>(
      {url: `/api/cau-hinh-don-vi`, method: 'GET',
        params
    },
      );
    }
  export const themMoi26 = (
    cauHinhDonViRequest: CauHinhDonViRequest,
 ) => {
      return customAxiosInstance<ApiResponseCauHinhDonViResponse>(
      {url: `/api/cau-hinh-don-vi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cauHinhDonViRequest
    },
      );
    }
  export const layCauHinhMine = (

 ) => {
      return customAxiosInstance<ApiResponseListCauHinhDonViResponse>(
      {url: `/api/cau-hinh-don-vi/mine`, method: 'GET'
    },
      );
    }
  export type LayTheoId26Result = NonNullable<Awaited<ReturnType<typeof layTheoId26>>>
export type CapNhat25Result = NonNullable<Awaited<ReturnType<typeof capNhat25>>>
export type XoaMem26Result = NonNullable<Awaited<ReturnType<typeof xoaMem26>>>
export type LayDanhSach26Result = NonNullable<Awaited<ReturnType<typeof layDanhSach26>>>
export type ThemMoi26Result = NonNullable<Awaited<ReturnType<typeof themMoi26>>>
export type LayCauHinhMineResult = NonNullable<Awaited<ReturnType<typeof layCauHinhMine>>>
