/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseListSelectOption,
  ApiResponseNhaCungCapResponse,
  ApiResponsePageResponseNhaCungCapResponse,
  ApiResponseString,
  LayDanhSach14Params,
  NhaCungCapRequest,
  TrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId14 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseNhaCungCapResponse>(
      {url: `/api/nha-cung-cap/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat14 = (
    id: number,
    nhaCungCapRequest: NhaCungCapRequest,
 ) => {
      return customAxiosInstance<ApiResponseNhaCungCapResponse>(
      {url: `/api/nha-cung-cap/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: nhaCungCapRequest
    },
      );
    }
  export const xoaMem14 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/nha-cung-cap/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai8 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/nha-cung-cap/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach14 = (
    params?: LayDanhSach14Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseNhaCungCapResponse>(
      {url: `/api/nha-cung-cap`, method: 'GET',
        params
    },
      );
    }
  export const themMoi14 = (
    nhaCungCapRequest: NhaCungCapRequest,
 ) => {
      return customAxiosInstance<ApiResponseNhaCungCapResponse>(
      {url: `/api/nha-cung-cap`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: nhaCungCapRequest
    },
      );
    }
  export const laySelectOptions5 = (

 ) => {
      return customAxiosInstance<ApiResponseListSelectOption>(
      {url: `/api/nha-cung-cap/select-options`, method: 'GET'
    },
      );
    }
  export type LayTheoId14Result = NonNullable<Awaited<ReturnType<typeof layTheoId14>>>
export type CapNhat14Result = NonNullable<Awaited<ReturnType<typeof capNhat14>>>
export type XoaMem14Result = NonNullable<Awaited<ReturnType<typeof xoaMem14>>>
export type CapNhatTrangThai8Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai8>>>
export type LayDanhSach14Result = NonNullable<Awaited<ReturnType<typeof layDanhSach14>>>
export type ThemMoi14Result = NonNullable<Awaited<ReturnType<typeof themMoi14>>>
export type LaySelectOptions5Result = NonNullable<Awaited<ReturnType<typeof laySelectOptions5>>>
