/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { AllocatedHardwareResponse } from './allocatedHardwareResponse';
import type { AllocatedLinhKienResponse } from './allocatedLinhKienResponse';
import type { AllocatedSoftwareResponse } from './allocatedSoftwareResponse';

export interface ActiveAllocationResponse {
  danhSachPhanCung?: AllocatedHardwareResponse[];
  danhSachPhanMem?: AllocatedSoftwareResponse[];
  danhSachLinhKien?: AllocatedLinhKienResponse[];
}
