/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { PageResponseDanhSachThietBiPhanMemResponse } from './pageResponseDanhSachThietBiPhanMemResponse';

export interface ApiResponsePageResponseDanhSachThietBiPhanMemResponse {
  code?: number;
  message?: string;
  data?: PageResponseDanhSachThietBiPhanMemResponse;
}
