/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

/**
 * Chi tiết một giá trị thuộc tính
 */
export interface AttributeValueItem {
  /** ID danh mục thuộc tính */
  danhMucThuocTinhId: number;
  /** ID lựa chọn gợi ý (nếu chọn từ option có sẵn) */
  luaChonId?: number;
  /** Giá trị tự nhập tay (hoặc đi kèm option Khác...) */
  giaTri?: string;
}
