/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

/**
 * Thông tin chi tiết tài sản trong phiếu điều chuyển
 */
export interface ChiTietDieuChuyenGeneralResponse {
  id?: number;
  /** ID vật lý của thiết bị hoặc linh kiện */
  idTaiSan?: number;
  /** ID dòng chi tiết cấp phát gốc tương ứng của người gửi */
  chiTietCapPhatId?: number;
  /** Tên mẫu tài sản */
  tenTaiSan?: string;
  /** Số Serial định danh vật lý */
  soSerial?: string;
  /** Mã thẻ tài sản (nếu là phần cứng, linh kiện trả về null) */
  maTheTaiSan?: string;
  /** Tình trạng thiết bị do người chuyển giao ghi nhận */
  trangThaiXuat?: string;
  /** Tình trạng thiết bị do đầu nhận đối soát thực tế */
  trangThaiNhan?: string;
  /** Phân loại vật tư điều chuyển (PHAN_CUNG hoặc LINH_KIEN) */
  loai?: string;
  ghiChu?: string;
}
