/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

export interface ChiTietTonKhoResponse {
  id?: number;
  idTaiSanCuThe?: number;
  tenTaiSanCuThe?: string;
  soSerial?: string;
  maTheTaiSan?: string;
  loaiTaiSan?: string;
  viTriKho?: string;
  trangThai?: string;
  idDotKiemKeGanNhat?: number;
  tenDotKiemKeGanNhat?: string;
  ghiChu?: string;
  thoiGianGhiNhan?: string;
}
