/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

/**
 * Thông tin chi tiết phẳng của đơn hàng mua sắm
 */
export interface ChiTietDonHangGeneralResponse {
  id?: number;
  idTaiSan?: number;
  tenTaiSan?: string;
  soLuongDat?: number;
  donGiaDat?: number;
  thanhTien?: number;
  soLuongDaNhap?: number;
  ghiChu?: string;
  loai?: string;
  thoiGianTao?: string;
  thoiGianCapNhat?: string;
}
