/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

export interface ChiTietKiemKeFlatResponse {
  id?: number;
  idTaiSanGoc?: number;
  tenTaiSan?: string;
  soSerial?: string;
  maTheTaiSan?: string;
  daKiemKeThucTe?: boolean;
  tinhTrangHoacBanQuyen?: string;
  viTriHoacThietBiCaiDat?: string;
  ketLuan?: string;
  ghiChu?: string;
  loaiTaiSan?: string;
}
