/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

/**
 * Thông tin chi tiết tài sản trong phiếu thanh lý
 */
export interface ChiTietThanhLyGeneralResponse {
  id?: number;
  /** ID vật lý của thiết bị/phần mềm/linh kiện */
  idTaiSan?: number;
  /** Tên mẫu tài sản */
  tenTaiSan?: string;
  /** Số Serial định danh */
  soSerial?: string;
  /** Mã thẻ tài sản (nếu có) */
  maTheTaiSan?: string;
  /** Giá trị thu hồi dự kiến khi thanh lý con máy này */
  tienThuHoi?: number;
  lýDoChiTiet?: string;
  loai?: string;
  ghiChu?: string;
}
