/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

/**
 * Thông tin chi tiết phẳng của phiếu nhập tài sản
 */
export interface ChiTietNhapTaiSanGeneralResponse {
  id?: number;
  /** ID của vật tư tài sản */
  idTaiSan?: number;
  /** Tên vật tư tài sản */
  tenTaiSan?: string;
  /** ID của thiết bị hoặc linh kiện thực nhập */
  idThietBi?: number;
  /** ID của chi tiết đơn hàng tương ứng */
  idChiTietDonHang?: number;
  /** Giá nhập thực tế */
  giaNhapThucTe?: number;
  /** Tình trạng lúc nhập */
  tinhTrangLucNhap?: string;
  /** Số lượng ghế nhập (dành cho phần mềm) */
  soLuongGheNhap?: number;
  /** Phân loại tài sản (PHAN_CUNG, LINH_KIEN, PHAN_MEM) */
  loai?: string;
  thoiGianTao?: string;
  thoiGianCapNhat?: string;
}
