/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

export interface ChiTietSuDungResponse {
  id?: number;
  idTaiSanCuThe?: number;
  tenTaiSanCuThe?: string;
  soSerial?: string;
  maTheTaiSan?: string;
  loaiTaiSan?: string;
  idNhanVienTiepNhan?: number;
  hoTenNhanVienTiepNhan?: string;
  idChungTuGoc?: number;
  maChungTuGoc?: string;
  tinhTrangBanGiao?: string;
  thoiGianThucHien?: string;
}
