/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

export interface ChiTietCapPhatPhanCungRequest {
  danhSachThietBiPhanCungId: number;
  /**
     * @minLength 0
     * @maxLength 100
     */
  tinhTrangLucGiao?: string;
  /**
     * @minLength 0
     * @maxLength 255
     */
  phuKienKemTheo?: string;
  ghiChu?: string;
}
