/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

/**
 * Thông tin chi tiết phẳng của phiếu thu hồi tài sản
 */
export interface ChiTietThuHoiGeneralResponse {
  id?: number;
  /** ID chi tiết cấp phát tương ứng */
  idChiTietCapPhat?: number;
  /** ID của thiết bị hoặc linh kiện được thu hồi */
  idTaiSan?: number;
  /** Tên tài sản (mẫu thiết bị/phần mềm/linh kiện) */
  tenTaiSan?: string;
  /** Số serial của thiết bị hoặc linh kiện */
  soSerial?: string;
  /** Mã thẻ tài sản (hoặc Key bản quyền đối với phần mềm) */
  maTheTaiSan?: string;
  /** Tình trạng lúc thu hồi */
  tinhTrangLucThuHoi?: string;
  /** Phụ kiện đi kèm thu hồi */
  phuKienThuHoi?: string;
  /** Thời gian thực hiện thu hồi (dành riêng cho phần mềm) */
  thoiGianThuHoi?: string;
  /** Ghi chú */
  ghiChu?: string;
  /** Phân loại tài sản (PHAN_CUNG, PHAN_MEM, LINH_KIEN) */
  loai?: string;
}
