/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

/**
 * Thông tin giá trị thuộc tính thực tế của tài sản
 */
export interface GiaTriThuocTinhResponse {
  /** ID giá trị thuộc tính */
  id?: number;
  /** ID đơn vị quản lý (Tenant ID) */
  idDonVi?: number;
  /** ID danh mục thuộc tính */
  danhMucThuocTinhId?: number;
  /** Tên thuộc tính */
  danhMucThuocTinhTen?: string;
  /** Mã thuộc tính */
  danhMucThuocTinhMa?: string;
  /** ID lựa chọn gợi ý (nếu chọn option có sẵn) */
  luaChonId?: number;
  /** Giá trị của lựa chọn gợi ý */
  luaChonGiaTri?: string;
  /** Loại tài sản (PHAN_CUNG, PHAN_MEM, LINH_KIEN) */
  loaiTaiSan?: string;
  /** ID tài sản cụ thể */
  idTaiSan?: number;
  /** Giá trị thực tế lưu trữ */
  giaTri?: string;
  /** Thời gian tạo */
  thoiGianTao?: string;
  /** Thời gian cập nhật */
  thoiGianCapNhat?: string;
}
