/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { AttributeValueItem } from './attributeValueItem';

/**
 * Yêu cầu lưu hàng loạt giá trị thuộc tính cho tài sản
 */
export interface GiaTriThuocTinhBulkSaveRequest {
  /**
     * Loại tài sản cấu hình (PHAN_CUNG, PHAN_MEM, LINH_KIEN)
     * @pattern PHAN_CUNG|PHAN_MEM|LINH_KIEN
     */
  loaiTaiSan: string;
  /** ID của thiết bị hoặc key bản quyền cụ thể */
  idTaiSan: number;
  /** Danh sách giá trị thuộc tính chi tiết */
  values: AttributeValueItem[];
}
