/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { ChiTietKeHoachBaoTriResponse } from './chiTietKeHoachBaoTriResponse';

export interface KeHoachBaoTriDinhKyResponse {
  id?: number;
  idDonVi?: number;
  maKeHoach?: string;
  tenKeHoach?: string;
  tenNguoiLap?: string;
  tenNguoiPheDuyet?: string;
  chuKyLap?: string;
  thoiGianBatDauKeHoach?: string;
  thoiGianKetThucKeHoach?: string;
  thoiGianLanCuoi?: string;
  thoiGianLanTiep?: string;
  chiPhiDuKien?: number;
  trangThai?: string;
  noiDungBaoTri?: string;
  thoiGianTao?: string;
  thoiGianCapNhat?: string;
  chiTietPhanVi?: ChiTietKeHoachBaoTriResponse[];
}
