/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

/**
 * Dữ liệu yêu cầu lắp ráp linh kiện vào thiết bị
 */
export interface LapRapLinhKienRequest {
  /** ID của thiết bị phần cứng tiếp nhận linh kiện */
  thietBiPhanCungId: number;
  /** ID của linh kiện phần cứng lẻ cần mang đi lắp ráp */
  linhKienPhanCungId: number;
  /** Ghi chú bổ sung khi thực hiện lắp ráp */
  ghiChu?: string;
}
