/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

/**
 * Dữ liệu phản hồi thông tin lịch sử tháo lắp linh kiện
 */
export interface LapRapLinhKienResponse {
  /** ID bản ghi liên kết tháo lắp */
  id?: number;
  /** ID thiết bị phần cứng */
  thietBiPhanCungId?: number;
  /** Số Serial của thiết bị phần cứng */
  soSerialThietBi?: string;
  /** Mã thẻ tài sản của thiết bị phần cứng */
  maTheTaiSanThietBi?: string;
  /** ID linh kiện phần cứng */
  linhKienPhanCungId?: number;
  /** Số Serial của linh kiện phần cứng */
  soSerialLinhKien?: string;
  /** Thời gian thực hiện lắp ráp */
  thoiGianLap?: string;
  /** Thời gian thực hiện tháo dỡ (null nếu đang liên kết) */
  thoiGianThao?: string;
  /** Trạng thái liên kết (ACTIVE: Đang gắn, INACTIVE: Đã tháo) */
  trangThaiLienKet?: string;
  /** Ghi chú tháo lắp */
  ghiChu?: string;
  /** Thời gian tạo bản ghi */
  thoiGianTao?: string;
  /** Thời gian cập nhật bản ghi */
  thoiGianCapNhat?: string;
}
