/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

export type LayDanhSach2Params = {
keyword?: string;
trangThai?: string;
tuNgayMua?: string;
denNgayMua?: string;
tuNgayHetHan?: string;
denNgayHetHan?: string;
trangThaiKho?: string;
page?: number;
size?: number;
sort?: string;
};
