/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

export type LayDanhSach28Params = {
id_tai_san?: number;
loai_tai_san?: string;
page?: number;
size?: number;
sort?: string;
};
