/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

/**
 * Thông tin lựa chọn gợi ý trả về
 */
export interface LuaChonGoiYResponse {
  /** ID lựa chọn */
  id?: number;
  /** ID danh mục thuộc tính cha */
  idDanhMucThuocTinh?: number;
  /** Giá trị gợi ý */
  giaTri?: string;
  /** Trạng thái */
  trangThai?: string;
  /** Thứ tự hiển thị */
  thuTuHienThi?: number;
  /** Thời gian tạo */
  thoiGianTao?: string;
  /** Thời gian cập nhật */
  thoiGianCapNhat?: string;
}
