/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

/**
 * Yêu cầu cấu hình một lựa chọn gợi ý lồng
 */
export interface LuaChonGoiYSubRequest {
  /** ID của lựa chọn gợi ý (null nếu thêm mới, có ID nếu cập nhật) */
  id?: number;
  /**
     * Giá trị hiển thị của lựa chọn
     * @minLength 0
     * @maxLength 150
     */
  giaTri: string;
  /**
     * Trạng thái hoạt động (HOAT_DONG/KHOA)
     * @minLength 0
     * @maxLength 30
     */
  trangThai: string;
  /** Thứ tự sắp xếp hiển thị */
  thuTuHienThi: number;
}
