/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { QuyenResponse } from './quyenResponse';
import type { VaiTroResponse } from './vaiTroResponse';

export interface NguoiDungResponse {
  id?: number;
  idDonVi?: number;
  idPhongBan?: number;
  tenPhongBan?: string;
  tenDangNhap?: string;
  hoNguoiDung?: string;
  tenDemNguoiDung?: string;
  tenNguoiDung?: string;
  chucVu?: string;
  email?: string;
  soDienThoai?: string;
  danhDaiDienUrl?: string;
  trangThai?: string;
  danhSachVaiTro?: VaiTroResponse[];
  danhSachQuyen?: QuyenResponse[];
  danhSachQuyenPhanGiai?: string[];
}
