/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { HangSanXuatResponse } from './hangSanXuatResponse';
import type { PageInfo } from './pageInfo';

export interface PageResponseHangSanXuatResponse {
  content?: HangSanXuatResponse[];
  page_info?: PageInfo;
}
