/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { DanhMucTaiSanResponse } from './danhMucTaiSanResponse';
import type { PageInfo } from './pageInfo';

export interface PageResponseDanhMucTaiSanResponse {
  content?: DanhMucTaiSanResponse[];
  page_info?: PageInfo;
}
