/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */

export interface PageInfo {
  current_page?: number;
  page_size?: number;
  total_elements?: number;
  total_pages?: number;
  is_last?: boolean;
  is_first?: boolean;
}
