/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { BaoCaoToanSanSuperAdminResponse } from './baoCaoToanSanSuperAdminResponse';
import type { PageInfo } from './pageInfo';

export interface PageResponseBaoCaoToanSanSuperAdminResponse {
  content?: BaoCaoToanSanSuperAdminResponse[];
  page_info?: PageInfo;
}
