/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { DonViResponse } from './donViResponse';
import type { PageInfo } from './pageInfo';

export interface PageResponseDonViResponse {
  content?: DonViResponse[];
  page_info?: PageInfo;
}
