/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { PageInfo } from './pageInfo';
import type { TaiSanPhanMemResponse } from './taiSanPhanMemResponse';

export interface PageResponseTaiSanPhanMemResponse {
  content?: TaiSanPhanMemResponse[];
  page_info?: PageInfo;
}
