/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { ChiTietThuHoiGeneralResponse } from './chiTietThuHoiGeneralResponse';

/**
 * Thông tin phản hồi của phiếu thu hồi tài sản
 */
export interface PhieuThuHoiTaiSanResponse {
  id?: number;
  idDonVi?: number;
  maPhieuThuHoi?: string;
  idNhanVienTra?: number;
  /** Tên nhân viên trả tài sản */
  tenNhanVienTra?: string;
  idPhongBanTra?: number;
  tenPhongBanTra?: string;
  /** Tên người lập phiếu thu hồi */
  tenNguoiLap?: string;
  /** Tên người phê duyệt phiếu thu hồi */
  tenNguoiPheDuyet?: string;
  lyDoThuHoi?: string;
  thoiGianThuHoi?: string;
  trangThai?: string;
  thoiGianTao?: string;
  thoiGianCapNhat?: string;
  /** Danh sách chi tiết tài sản thu hồi */
  chiTietTaiSan?: ChiTietThuHoiGeneralResponse[];
}
