/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { ChiTietNhapTaiSanGeneralResponse } from './chiTietNhapTaiSanGeneralResponse';

/**
 * Thông tin phản hồi của phiếu nhập tài sản
 */
export interface PhieuNhapTaiSanResponse {
  id?: number;
  idDonVi?: number;
  idDonHangMuaSam?: number;
  maDonHangMuaSam?: string;
  /** Tên người thực hiện nhập kho */
  tenNguoiNhap?: string;
  maPhieuNhap?: string;
  soHoaDonVat?: string;
  maBienBanGiaoHang?: string;
  thoiGianNhapKho?: string;
  trangThai?: string;
  ghiChu?: string;
  thoiGianTao?: string;
  thoiGianCapNhat?: string;
  /** Danh sách chi tiết tài sản của phiếu nhập */
  chiTietTaiSan?: ChiTietNhapTaiSanGeneralResponse[];
}
