/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { ChiTietBaoTriGeneralResponse } from './chiTietBaoTriGeneralResponse';

export interface PhieuSuaChuaBaoTriResponse {
  id?: number;
  idDonVi?: number;
  keHoachBaoTriId?: number;
  maPhieuSuaChua?: string;
  tenNguoiLap?: string;
  tenNguoiPheDuyet?: string;
  thoiGianLapPhieu?: string;
  thoiGianBatDau?: string;
  thoiGianHoanThanhDuKien?: string;
  thoiGianHoanThanhThucTe?: string;
  tongChiPhiThucHien?: number;
  trangThai?: string;
  ghiChu?: string;
  thoiGianTao?: string;
  thoiGianCapNhat?: string;
  chiTietTaiSan?: ChiTietBaoTriGeneralResponse[];
}
