/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { ChiTietNhapLinhKienRequest } from './chiTietNhapLinhKienRequest';
import type { ChiTietNhapPhanCungRequest } from './chiTietNhapPhanCungRequest';
import type { ChiTietNhapPhanMemRequest } from './chiTietNhapPhanMemRequest';

export interface PhieuNhapTaiSanRequest {
  idDonHangMuaSam: number;
  idNguoiNhap?: number;
  /**
     * @minLength 0
     * @maxLength 50
     */
  maPhieuNhap?: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  soHoaDonVat?: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  maBienBanGiaoHang?: string;
  thoiGianNhapKho?: string;
  ghiChu?: string;
  chiTietPhanCung?: ChiTietNhapPhanCungRequest[];
  chiTietLinhKien?: ChiTietNhapLinhKienRequest[];
  chiTietPhanMem?: ChiTietNhapPhanMemRequest[];
}
