/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { ChiTietThuHoiLinhKienRequest } from './chiTietThuHoiLinhKienRequest';
import type { ChiTietThuHoiPhanCungRequest } from './chiTietThuHoiPhanCungRequest';
import type { ChiTietThuHoiPhanMemRequest } from './chiTietThuHoiPhanMemRequest';

export interface PhieuThuHoiTaiSanRequest {
  idNhanVienTra: number;
  idPhongBanTra: number;
  lyDoThuHoi?: string;
  danhSachPhanCung?: ChiTietThuHoiPhanCungRequest[];
  danhSachPhanMem?: ChiTietThuHoiPhanMemRequest[];
  danhSachLinhKien?: ChiTietThuHoiLinhKienRequest[];
}
