/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { ChiTietDieuChuyenLinhKienRequest } from './chiTietDieuChuyenLinhKienRequest';
import type { ChiTietDieuChuyenPhanCungRequest } from './chiTietDieuChuyenPhanCungRequest';

export interface PhieuDieuChuyenTaiSanRequest {
  idNguoiChuyen: number;
  idPhongBanChuyen: number;
  idNguoiNhan: number;
  idPhongBanNhan: number;
  lyDoDieuChuyen?: string;
  danhSachPhanCung?: ChiTietDieuChuyenPhanCungRequest[];
  danhSachLinhKien?: ChiTietDieuChuyenLinhKienRequest[];
}
