/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { ChiTietDieuChuyenGeneralResponse } from './chiTietDieuChuyenGeneralResponse';

export interface PhieuDieuChuyenTaiSanResponse {
  id?: number;
  idDonVi?: number;
  maPhieuDieuChuyen?: string;
  idNguoiChuyen?: number;
  tenNguoiChuyen?: string;
  idPhongBanChuyen?: number;
  tenPhongBanChuyen?: string;
  idNguoiNhan?: number;
  tenNguoiNhan?: string;
  idPhongBanNhan?: number;
  tenPhongBanNhan?: string;
  tenNguoiLap?: string;
  tenNguoiPheDuyet?: string;
  lyDoDieuChuyen?: string;
  thoiGianBanGiao?: string;
  trangThai?: string;
  thoiGianTao?: string;
  thoiGianCapNhat?: string;
  /** Danh sách gộp phẳng toàn bộ thiết bị và linh kiện của phiếu điều chuyển */
  chiTietTaiSan?: ChiTietDieuChuyenGeneralResponse[];
}
