/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { TaiSanCapPhatResponse } from './taiSanCapPhatResponse';

export interface TaiSanTheoPhongBanResponse {
  idPhongBan?: number;
  danhSachPhanCung?: TaiSanCapPhatResponse[];
  danhSachLinhKien?: TaiSanCapPhatResponse[];
  danhSachPhanMem?: TaiSanCapPhatResponse[];
}
