/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { QuyenResponse } from './quyenResponse';

export interface VaiTroResponse {
  id?: number;
  idDonVi?: number;
  maVaiTro?: string;
  tenVaiTro?: string;
  moTa?: string;
  trangThai?: string;
  laHeThong?: boolean;
  capDoUuTien?: number;
  danhSachQuyen?: QuyenResponse[];
}
