/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type { NguoiDungResponse } from './nguoiDungResponse';

export interface XacThucResponse {
  accessToken?: string;
  refreshToken?: string;
  idDonVi?: number;
  username?: string;
  thongTinNguoiDung?: NguoiDungResponse;
}
