/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponsePageResponsePhieuDieuChuyenTaiSanResponse,
  ApiResponsePhieuDieuChuyenTaiSanResponse,
  ApiResponseString,
  LayDanhSach12Params,
  PhieuDieuChuyenTaiSanRequest,
  TuChoiPheDuyet2Params
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId12 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponsePhieuDieuChuyenTaiSanResponse>(
      {url: `/api/phieu-dieu-chuyen/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat12 = (
    id: number,
    phieuDieuChuyenTaiSanRequest: PhieuDieuChuyenTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuDieuChuyenTaiSanResponse>(
      {url: `/api/phieu-dieu-chuyen/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: phieuDieuChuyenTaiSanRequest
    },
      );
    }
  export const xoaMem12 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-dieu-chuyen/${id}`, method: 'DELETE'
    },
      );
    }
  export const yeuCauPheDuyet3 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-dieu-chuyen/${id}/yeu-cau-phe-duyet`, method: 'PUT'
    },
      );
    }
  export const tuChoiPheDuyet2 = (
    id: number,
    params: TuChoiPheDuyet2Params,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-dieu-chuyen/${id}/tu-choi`, method: 'PUT',
        params
    },
      );
    }
  export const pheDuyet3 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-dieu-chuyen/${id}/phe-duyet`, method: 'PUT'
    },
      );
    }
  export const hoanThanh2 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-dieu-chuyen/${id}/hoan-thanh`, method: 'PUT'
    },
      );
    }
  export const layDanhSach12 = (
    params?: LayDanhSach12Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponsePhieuDieuChuyenTaiSanResponse>(
      {url: `/api/phieu-dieu-chuyen`, method: 'GET',
        params
    },
      );
    }
  export const themMoi12 = (
    phieuDieuChuyenTaiSanRequest: PhieuDieuChuyenTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuDieuChuyenTaiSanResponse>(
      {url: `/api/phieu-dieu-chuyen`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: phieuDieuChuyenTaiSanRequest
    },
      );
    }
  export type LayTheoId12Result = NonNullable<Awaited<ReturnType<typeof layTheoId12>>>
export type CapNhat12Result = NonNullable<Awaited<ReturnType<typeof capNhat12>>>
export type XoaMem12Result = NonNullable<Awaited<ReturnType<typeof xoaMem12>>>
export type YeuCauPheDuyet3Result = NonNullable<Awaited<ReturnType<typeof yeuCauPheDuyet3>>>
export type TuChoiPheDuyet2Result = NonNullable<Awaited<ReturnType<typeof tuChoiPheDuyet2>>>
export type PheDuyet3Result = NonNullable<Awaited<ReturnType<typeof pheDuyet3>>>
export type HoanThanh2Result = NonNullable<Awaited<ReturnType<typeof hoanThanh2>>>
export type LayDanhSach12Result = NonNullable<Awaited<ReturnType<typeof layDanhSach12>>>
export type ThemMoi12Result = NonNullable<Awaited<ReturnType<typeof themMoi12>>>
