/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseListSelectOption,
  ApiResponsePageResponsePhongBanResponse,
  ApiResponsePhongBanResponse,
  ApiResponseString,
  LayDanhSach6Params,
  LaySelectOptions4Params,
  PhongBanRequest,
  TrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId6 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponsePhongBanResponse>(
      {url: `/api/phong-ban/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat6 = (
    id: number,
    phongBanRequest: PhongBanRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhongBanResponse>(
      {url: `/api/phong-ban/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: phongBanRequest
    },
      );
    }
  export const xoaMem6 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phong-ban/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai6 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phong-ban/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach6 = (
    params?: LayDanhSach6Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponsePhongBanResponse>(
      {url: `/api/phong-ban`, method: 'GET',
        params
    },
      );
    }
  export const themMoi6 = (
    phongBanRequest: PhongBanRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhongBanResponse>(
      {url: `/api/phong-ban`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: phongBanRequest
    },
      );
    }
  export const laySelectOptions4 = (
    params?: LaySelectOptions4Params,
 ) => {
      return customAxiosInstance<ApiResponseListSelectOption>(
      {url: `/api/phong-ban/select-options`, method: 'GET',
        params
    },
      );
    }
  export type LayTheoId6Result = NonNullable<Awaited<ReturnType<typeof layTheoId6>>>
export type CapNhat6Result = NonNullable<Awaited<ReturnType<typeof capNhat6>>>
export type XoaMem6Result = NonNullable<Awaited<ReturnType<typeof xoaMem6>>>
export type CapNhatTrangThai6Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai6>>>
export type LayDanhSach6Result = NonNullable<Awaited<ReturnType<typeof layDanhSach6>>>
export type ThemMoi6Result = NonNullable<Awaited<ReturnType<typeof themMoi6>>>
export type LaySelectOptions4Result = NonNullable<Awaited<ReturnType<typeof laySelectOptions4>>>
