/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseNguoiDungResponse,
  ApiResponsePageResponseNguoiDungResponse,
  ApiResponseString,
  LayDanhSach15Params,
  NguoiDungQuyenUpdateRequest,
  NguoiDungRequest,
  NguoiDungTrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId15 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseNguoiDungResponse>(
      {url: `/api/nguoi-dung/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat15 = (
    id: number,
    nguoiDungRequest: NguoiDungRequest,
 ) => {
      return customAxiosInstance<ApiResponseNguoiDungResponse>(
      {url: `/api/nguoi-dung/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: nguoiDungRequest
    },
      );
    }
  export const xoaMem15 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/nguoi-dung/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai9 = (
    id: number,
    nguoiDungTrangThaiRequest: NguoiDungTrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/nguoi-dung/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: nguoiDungTrangThaiRequest
    },
      );
    }
  export const capNhatQuyen1 = (
    id: number,
    nguoiDungQuyenUpdateRequest: NguoiDungQuyenUpdateRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/nguoi-dung/${id}/quyen`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: nguoiDungQuyenUpdateRequest
    },
      );
    }
  export const layDanhSach15 = (
    params?: LayDanhSach15Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseNguoiDungResponse>(
      {url: `/api/nguoi-dung`, method: 'GET',
        params
    },
      );
    }
  export const themMoi15 = (
    nguoiDungRequest: NguoiDungRequest,
 ) => {
      return customAxiosInstance<ApiResponseNguoiDungResponse>(
      {url: `/api/nguoi-dung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: nguoiDungRequest
    },
      );
    }
  export const thuHoiPhien = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/nguoi-dung/${id}/thu-hoi-phien`, method: 'POST'
    },
      );
    }
  export type LayTheoId15Result = NonNullable<Awaited<ReturnType<typeof layTheoId15>>>
export type CapNhat15Result = NonNullable<Awaited<ReturnType<typeof capNhat15>>>
export type XoaMem15Result = NonNullable<Awaited<ReturnType<typeof xoaMem15>>>
export type CapNhatTrangThai9Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai9>>>
export type CapNhatQuyen1Result = NonNullable<Awaited<ReturnType<typeof capNhatQuyen1>>>
export type LayDanhSach15Result = NonNullable<Awaited<ReturnType<typeof layDanhSach15>>>
export type ThemMoi15Result = NonNullable<Awaited<ReturnType<typeof themMoi15>>>
export type ThuHoiPhienResult = NonNullable<Awaited<ReturnType<typeof thuHoiPhien>>>
