/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseListGiaTriThuocTinhResponse,
  ApiResponsePageResponseGiaTriThuocTinhResponse,
  GiaTriThuocTinhBulkSaveRequest,
  LayDanhSach28Params
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const saveBulk = (
    giaTriThuocTinhBulkSaveRequest: GiaTriThuocTinhBulkSaveRequest,
 ) => {
      return customAxiosInstance<ApiResponseListGiaTriThuocTinhResponse>(
      {url: `/api/gia-tri-thuoc-tinh/save-bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: giaTriThuocTinhBulkSaveRequest
    },
      );
    }
  export const layDanhSach28 = (
    params?: LayDanhSach28Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseGiaTriThuocTinhResponse>(
      {url: `/api/gia-tri-thuoc-tinh`, method: 'GET',
        params
    },
      );
    }
  export type SaveBulkResult = NonNullable<Awaited<ReturnType<typeof saveBulk>>>
export type LayDanhSach28Result = NonNullable<Awaited<ReturnType<typeof layDanhSach28>>>
