/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseMapStringObject,
  ApiResponseThongKeTongQuanDashboardResponse
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layThongKeToanSanSuperAdmin = (

 ) => {
      return customAxiosInstance<ApiResponseMapStringObject>(
      {url: `/api/dashboard/toan-san`, method: 'GET'
    },
      );
    }
  export const layThongKeDonViAdmin = (

 ) => {
      return customAxiosInstance<ApiResponseThongKeTongQuanDashboardResponse>(
      {url: `/api/dashboard/don-vi`, method: 'GET'
    },
      );
    }
  export type LayThongKeToanSanSuperAdminResult = NonNullable<Awaited<ReturnType<typeof layThongKeToanSanSuperAdmin>>>
export type LayThongKeDonViAdminResult = NonNullable<Awaited<ReturnType<typeof layThongKeDonViAdmin>>>
