/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponsePageResponseBaoCaoBaoTriResponse,
  ApiResponsePageResponseBaoCaoCapPhatResponse,
  ApiResponsePageResponseBaoCaoToanSanSuperAdminResponse,
  ApiResponsePageResponseBaoCaoTonKhoResponse,
  LayBaoCaoBaoTriParams,
  LayBaoCaoCapPhatParams,
  LayBaoCaoTonKhoParams,
  LayTongHopToanSanSuperAdminParams,
  XuatFileBaoCaoParams
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const xuatFileBaoCao = (
    params: XuatFileBaoCaoParams,
 ) => {
      return customAxiosInstance<string>(
      {url: `/api/bao-cao/xuat-file`, method: 'GET',
        params
    },
      );
    }
  export const layBaoCaoTonKho = (
    params: LayBaoCaoTonKhoParams,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseBaoCaoTonKhoResponse>(
      {url: `/api/bao-cao/ton-kho`, method: 'GET',
        params
    },
      );
    }
  export const layTongHopToanSanSuperAdmin = (
    params?: LayTongHopToanSanSuperAdminParams,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseBaoCaoToanSanSuperAdminResponse>(
      {url: `/api/bao-cao/toan-san`, method: 'GET',
        params
    },
      );
    }
  export const xuatFileBaoCaoToanSanSuperAdmin = (

 ) => {
      return customAxiosInstance<string>(
      {url: `/api/bao-cao/toan-san/xuat-file`, method: 'GET'
    },
      );
    }
  export const layBaoCaoCapPhat = (
    params: LayBaoCaoCapPhatParams,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseBaoCaoCapPhatResponse>(
      {url: `/api/bao-cao/cap-phat`, method: 'GET',
        params
    },
      );
    }
  export const layBaoCaoBaoTri = (
    params: LayBaoCaoBaoTriParams,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseBaoCaoBaoTriResponse>(
      {url: `/api/bao-cao/bao-tri`, method: 'GET',
        params
    },
      );
    }
  export type XuatFileBaoCaoResult = NonNullable<Awaited<ReturnType<typeof xuatFileBaoCao>>>
export type LayBaoCaoTonKhoResult = NonNullable<Awaited<ReturnType<typeof layBaoCaoTonKho>>>
export type LayTongHopToanSanSuperAdminResult = NonNullable<Awaited<ReturnType<typeof layTongHopToanSanSuperAdmin>>>
export type XuatFileBaoCaoToanSanSuperAdminResult = NonNullable<Awaited<ReturnType<typeof xuatFileBaoCaoToanSanSuperAdmin>>>
export type LayBaoCaoCapPhatResult = NonNullable<Awaited<ReturnType<typeof layBaoCaoCapPhat>>>
export type LayBaoCaoBaoTriResult = NonNullable<Awaited<ReturnType<typeof layBaoCaoBaoTri>>>
