/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponsePageResponsePhieuNhapTaiSanResponse,
  ApiResponsePhieuNhapTaiSanResponse,
  ApiResponseString,
  LayDanhSach10Params,
  PhieuNhapTaiSanRequest,
  TrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId10 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponsePhieuNhapTaiSanResponse>(
      {url: `/api/phieu-nhap-tai-san/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat10 = (
    id: number,
    phieuNhapTaiSanRequest: PhieuNhapTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuNhapTaiSanResponse>(
      {url: `/api/phieu-nhap-tai-san/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: phieuNhapTaiSanRequest
    },
      );
    }
  export const xoaMem10 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-nhap-tai-san/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai7 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-nhap-tai-san/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach10 = (
    params?: LayDanhSach10Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponsePhieuNhapTaiSanResponse>(
      {url: `/api/phieu-nhap-tai-san`, method: 'GET',
        params
    },
      );
    }
  export const themMoi10 = (
    phieuNhapTaiSanRequest: PhieuNhapTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuNhapTaiSanResponse>(
      {url: `/api/phieu-nhap-tai-san`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: phieuNhapTaiSanRequest
    },
      );
    }
  export type LayTheoId10Result = NonNullable<Awaited<ReturnType<typeof layTheoId10>>>
export type CapNhat10Result = NonNullable<Awaited<ReturnType<typeof capNhat10>>>
export type XoaMem10Result = NonNullable<Awaited<ReturnType<typeof xoaMem10>>>
export type CapNhatTrangThai7Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai7>>>
export type LayDanhSach10Result = NonNullable<Awaited<ReturnType<typeof layDanhSach10>>>
export type ThemMoi10Result = NonNullable<Awaited<ReturnType<typeof themMoi10>>>
