/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseListSelectOption,
  ApiResponsePageResponseTaiSanPhanCungResponse,
  ApiResponseString,
  ApiResponseTaiSanPhanCungResponse,
  LayDanhSach5Params,
  TaiSanPhanCungRequest,
  TrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId5 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseTaiSanPhanCungResponse>(
      {url: `/api/tai-san-phan-cung/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat5 = (
    id: number,
    taiSanPhanCungRequest: TaiSanPhanCungRequest,
 ) => {
      return customAxiosInstance<ApiResponseTaiSanPhanCungResponse>(
      {url: `/api/tai-san-phan-cung/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: taiSanPhanCungRequest
    },
      );
    }
  export const xoaMem5 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/tai-san-phan-cung/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai5 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/tai-san-phan-cung/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach5 = (
    params?: LayDanhSach5Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseTaiSanPhanCungResponse>(
      {url: `/api/tai-san-phan-cung`, method: 'GET',
        params
    },
      );
    }
  export const themMoi5 = (
    taiSanPhanCungRequest: TaiSanPhanCungRequest,
 ) => {
      return customAxiosInstance<ApiResponseTaiSanPhanCungResponse>(
      {url: `/api/tai-san-phan-cung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taiSanPhanCungRequest
    },
      );
    }
  export const laySelectOptions3 = (

 ) => {
      return customAxiosInstance<ApiResponseListSelectOption>(
      {url: `/api/tai-san-phan-cung/select-options`, method: 'GET'
    },
      );
    }
  export type LayTheoId5Result = NonNullable<Awaited<ReturnType<typeof layTheoId5>>>
export type CapNhat5Result = NonNullable<Awaited<ReturnType<typeof capNhat5>>>
export type XoaMem5Result = NonNullable<Awaited<ReturnType<typeof xoaMem5>>>
export type CapNhatTrangThai5Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai5>>>
export type LayDanhSach5Result = NonNullable<Awaited<ReturnType<typeof layDanhSach5>>>
export type ThemMoi5Result = NonNullable<Awaited<ReturnType<typeof themMoi5>>>
export type LaySelectOptions3Result = NonNullable<Awaited<ReturnType<typeof laySelectOptions3>>>
