/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseDonHangMuaSamResponse,
  ApiResponseListSelectOption,
  ApiResponsePageResponseDonHangMuaSamResponse,
  ApiResponseString,
  DonHangMuaSamRequest,
  LayDanhSach22Params,
  LaySelectOptions10Params
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId22 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseDonHangMuaSamResponse>(
      {url: `/api/don-hang-mua-sam/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat21 = (
    id: number,
    donHangMuaSamRequest: DonHangMuaSamRequest,
 ) => {
      return customAxiosInstance<ApiResponseDonHangMuaSamResponse>(
      {url: `/api/don-hang-mua-sam/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: donHangMuaSamRequest
    },
      );
    }
  export const xoaMem22 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/don-hang-mua-sam/${id}`, method: 'DELETE'
    },
      );
    }
  export const yeuCauPheDuyet7 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/don-hang-mua-sam/${id}/yeu-cau-phe-duyet`, method: 'PUT'
    },
      );
    }
  export const pheDuyet7 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/don-hang-mua-sam/${id}/phe-duyet`, method: 'PUT'
    },
      );
    }
  export const layDanhSach22 = (
    params?: LayDanhSach22Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseDonHangMuaSamResponse>(
      {url: `/api/don-hang-mua-sam`, method: 'GET',
        params
    },
      );
    }
  export const themMoi22 = (
    donHangMuaSamRequest: DonHangMuaSamRequest,
 ) => {
      return customAxiosInstance<ApiResponseDonHangMuaSamResponse>(
      {url: `/api/don-hang-mua-sam`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: donHangMuaSamRequest
    },
      );
    }
  export const laySelectOptions10 = (
    params?: LaySelectOptions10Params,
 ) => {
      return customAxiosInstance<ApiResponseListSelectOption>(
      {url: `/api/don-hang-mua-sam/select-options`, method: 'GET',
        params
    },
      );
    }
  export type LayTheoId22Result = NonNullable<Awaited<ReturnType<typeof layTheoId22>>>
export type CapNhat21Result = NonNullable<Awaited<ReturnType<typeof capNhat21>>>
export type XoaMem22Result = NonNullable<Awaited<ReturnType<typeof xoaMem22>>>
export type YeuCauPheDuyet7Result = NonNullable<Awaited<ReturnType<typeof yeuCauPheDuyet7>>>
export type PheDuyet7Result = NonNullable<Awaited<ReturnType<typeof pheDuyet7>>>
export type LayDanhSach22Result = NonNullable<Awaited<ReturnType<typeof layDanhSach22>>>
export type ThemMoi22Result = NonNullable<Awaited<ReturnType<typeof themMoi22>>>
export type LaySelectOptions10Result = NonNullable<Awaited<ReturnType<typeof laySelectOptions10>>>
