/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseDanhMucCauHinhResponse,
  ApiResponsePageResponseDanhMucCauHinhResponse,
  ApiResponseString,
  DanhMucCauHinhRequest,
  LayDanhSach25Params
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId25 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseDanhMucCauHinhResponse>(
      {url: `/api/danh-muc-cau-hinh/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat24 = (
    id: number,
    danhMucCauHinhRequest: DanhMucCauHinhRequest,
 ) => {
      return customAxiosInstance<ApiResponseDanhMucCauHinhResponse>(
      {url: `/api/danh-muc-cau-hinh/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: danhMucCauHinhRequest
    },
      );
    }
  export const xoaMem25 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/danh-muc-cau-hinh/${id}`, method: 'DELETE'
    },
      );
    }
  export const layDanhSach25 = (
    params?: LayDanhSach25Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseDanhMucCauHinhResponse>(
      {url: `/api/danh-muc-cau-hinh`, method: 'GET',
        params
    },
      );
    }
  export const themMoi25 = (
    danhMucCauHinhRequest: DanhMucCauHinhRequest,
 ) => {
      return customAxiosInstance<ApiResponseDanhMucCauHinhResponse>(
      {url: `/api/danh-muc-cau-hinh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: danhMucCauHinhRequest
    },
      );
    }
  export type LayTheoId25Result = NonNullable<Awaited<ReturnType<typeof layTheoId25>>>
export type CapNhat24Result = NonNullable<Awaited<ReturnType<typeof capNhat24>>>
export type XoaMem25Result = NonNullable<Awaited<ReturnType<typeof xoaMem25>>>
export type LayDanhSach25Result = NonNullable<Awaited<ReturnType<typeof layDanhSach25>>>
export type ThemMoi25Result = NonNullable<Awaited<ReturnType<typeof themMoi25>>>
