/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseNguoiDungResponse,
  ApiResponseString,
  ApiResponseXacThucResponse,
  DangNhapRequest,
  DatLaiMatKhauRequest,
  DoiMatKhauRequest,
  LogoutRequest,
  QuenMatKhauRequest,
  RefreshTokenRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const refreshToken = (
    refreshTokenRequest: RefreshTokenRequest,
 ) => {
      return customAxiosInstance<ApiResponseXacThucResponse>(
      {url: `/api/auth/refresh-token`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenRequest
    },
      );
    }
  export const quenMatKhau = (
    quenMatKhauRequest: QuenMatKhauRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/auth/quen-mat-khau`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: quenMatKhauRequest
    },
      );
    }
  export const logout = (
    logoutRequest: LogoutRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: logoutRequest
    },
      );
    }
  export const login = (
    dangNhapRequest: DangNhapRequest,
 ) => {
      return customAxiosInstance<ApiResponseXacThucResponse>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dangNhapRequest
    },
      );
    }
  export const doiMatKhau = (
    doiMatKhauRequest: DoiMatKhauRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/auth/doi-mat-khau`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: doiMatKhauRequest
    },
      );
    }
  export const datLaiMatKhau = (
    datLaiMatKhauRequest: DatLaiMatKhauRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/auth/dat-lai-mat-khau`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: datLaiMatKhauRequest
    },
      );
    }
  export const getMyProfile = (

 ) => {
      return customAxiosInstance<ApiResponseNguoiDungResponse>(
      {url: `/api/auth/me`, method: 'GET'
    },
      );
    }
  export type RefreshTokenResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
export type QuenMatKhauResult = NonNullable<Awaited<ReturnType<typeof quenMatKhau>>>
export type LogoutResult = NonNullable<Awaited<ReturnType<typeof logout>>>
export type LoginResult = NonNullable<Awaited<ReturnType<typeof login>>>
export type DoiMatKhauResult = NonNullable<Awaited<ReturnType<typeof doiMatKhau>>>
export type DatLaiMatKhauResult = NonNullable<Awaited<ReturnType<typeof datLaiMatKhau>>>
export type GetMyProfileResult = NonNullable<Awaited<ReturnType<typeof getMyProfile>>>
