/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseDanhMucThuocTinhResponse,
  ApiResponsePageResponseDanhMucThuocTinhResponse,
  ApiResponseString,
  DanhMucThuocTinhRequest,
  LayDanhSach23Params,
  TrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId23 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseDanhMucThuocTinhResponse>(
      {url: `/api/danh-muc-thuoc-tinh/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat22 = (
    id: number,
    danhMucThuocTinhRequest: DanhMucThuocTinhRequest,
 ) => {
      return customAxiosInstance<ApiResponseDanhMucThuocTinhResponse>(
      {url: `/api/danh-muc-thuoc-tinh/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: danhMucThuocTinhRequest
    },
      );
    }
  export const xoaMem23 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/danh-muc-thuoc-tinh/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai14 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/danh-muc-thuoc-tinh/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach23 = (
    params?: LayDanhSach23Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseDanhMucThuocTinhResponse>(
      {url: `/api/danh-muc-thuoc-tinh`, method: 'GET',
        params
    },
      );
    }
  export const themMoi23 = (
    danhMucThuocTinhRequest: DanhMucThuocTinhRequest,
 ) => {
      return customAxiosInstance<ApiResponseDanhMucThuocTinhResponse>(
      {url: `/api/danh-muc-thuoc-tinh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: danhMucThuocTinhRequest
    },
      );
    }
  export type LayTheoId23Result = NonNullable<Awaited<ReturnType<typeof layTheoId23>>>
export type CapNhat22Result = NonNullable<Awaited<ReturnType<typeof capNhat22>>>
export type XoaMem23Result = NonNullable<Awaited<ReturnType<typeof xoaMem23>>>
export type CapNhatTrangThai14Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai14>>>
export type LayDanhSach23Result = NonNullable<Awaited<ReturnType<typeof layDanhSach23>>>
export type ThemMoi23Result = NonNullable<Awaited<ReturnType<typeof themMoi23>>>
