/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseListLuaChonDotKiemKeResponse,
  ApiResponseListTienDoPhongBanResponse,
  ApiResponsePageResponsePhieuKiemKeResponse,
  ApiResponsePhieuKiemKeResponse,
  ApiResponseString,
  ApiResponseTaiSanTheoPhongBanResponse,
  ExecuteKiemKeRequest,
  LayDanhSach11Params,
  LayTaiSanTheoPhongBanParams,
  PhieuKiemKeRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId11 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponsePhieuKiemKeResponse>(
      {url: `/api/phieu-kiem-ke/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat11 = (
    id: number,
    phieuKiemKeRequest: PhieuKiemKeRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuKiemKeResponse>(
      {url: `/api/phieu-kiem-ke/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: phieuKiemKeRequest
    },
      );
    }
  export const xoaMem11 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-kiem-ke/${id}`, method: 'DELETE'
    },
      );
    }
  export const xacNhanHoanThanhPhongBan = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-kiem-ke/${id}/xac-nhan-hoan-thanh`, method: 'PUT'
    },
      );
    }
  export const thucHienKiemKe = (
    id: number,
    executeKiemKeRequest: ExecuteKiemKeRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-kiem-ke/${id}/thuc-hien-kiem-ke`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: executeKiemKeRequest
    },
      );
    }
  export const layDanhSach11 = (
    params?: LayDanhSach11Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponsePhieuKiemKeResponse>(
      {url: `/api/phieu-kiem-ke`, method: 'GET',
        params
    },
      );
    }
  export const themMoi11 = (
    phieuKiemKeRequest: PhieuKiemKeRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuKiemKeResponse>(
      {url: `/api/phieu-kiem-ke`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: phieuKiemKeRequest
    },
      );
    }
  export const theoDoiTienDoThucHien = (
    dotKiemKeId: number,
 ) => {
      return customAxiosInstance<ApiResponseListTienDoPhongBanResponse>(
      {url: `/api/phieu-kiem-ke/tien-do/${dotKiemKeId}`, method: 'GET'
    },
      );
    }
  export const layTaiSanTheoPhongBan = (
    params: LayTaiSanTheoPhongBanParams,
 ) => {
      return customAxiosInstance<ApiResponseTaiSanTheoPhongBanResponse>(
      {url: `/api/phieu-kiem-ke/bo-tro/taisantheophong`, method: 'GET',
        params
    },
      );
    }
  export const layDotKiemKeKichHoat = (

 ) => {
      return customAxiosInstance<ApiResponseListLuaChonDotKiemKeResponse>(
      {url: `/api/phieu-kiem-ke/bo-tro/dotkiemkekichhoat`, method: 'GET'
    },
      );
    }
  export type LayTheoId11Result = NonNullable<Awaited<ReturnType<typeof layTheoId11>>>
export type CapNhat11Result = NonNullable<Awaited<ReturnType<typeof capNhat11>>>
export type XoaMem11Result = NonNullable<Awaited<ReturnType<typeof xoaMem11>>>
export type XacNhanHoanThanhPhongBanResult = NonNullable<Awaited<ReturnType<typeof xacNhanHoanThanhPhongBan>>>
export type ThucHienKiemKeResult = NonNullable<Awaited<ReturnType<typeof thucHienKiemKe>>>
export type LayDanhSach11Result = NonNullable<Awaited<ReturnType<typeof layDanhSach11>>>
export type ThemMoi11Result = NonNullable<Awaited<ReturnType<typeof themMoi11>>>
export type TheoDoiTienDoThucHienResult = NonNullable<Awaited<ReturnType<typeof theoDoiTienDoThucHien>>>
export type LayTaiSanTheoPhongBanResult = NonNullable<Awaited<ReturnType<typeof layTaiSanTheoPhongBan>>>
export type LayDotKiemKeKichHoatResult = NonNullable<Awaited<ReturnType<typeof layDotKiemKeKichHoat>>>
