/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseCheckDomainResponse,
  ApiResponseDonViResponse,
  ApiResponsePageResponseDonViResponse,
  ApiResponseString,
  CheckDomainParams,
  DangKyDonViRequest,
  DonViTrangThaiRequest,
  DonViUpdateRequest,
  GiaHanHopDongRequest,
  LayDanhSach29Params,
  XacThucOtpRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId21 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseDonViResponse>(
      {url: `/api/don-vi/${id}`, method: 'GET'
    },
      );
    }
  export const capNhatThongTin = (
    id: number,
    donViUpdateRequest: DonViUpdateRequest,
 ) => {
      return customAxiosInstance<ApiResponseDonViResponse>(
      {url: `/api/don-vi/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: donViUpdateRequest
    },
      );
    }
  export const xoaMem21 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/don-vi/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai13 = (
    id: number,
    donViTrangThaiRequest: DonViTrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/don-vi/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: donViTrangThaiRequest
    },
      );
    }
  export const giaHanHopDong = (
    id: number,
    giaHanHopDongRequest: GiaHanHopDongRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/don-vi/${id}/gia-han`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: giaHanHopDongRequest
    },
      );
    }
  export const xacThucOtp = (
    xacThucOtpRequest: XacThucOtpRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/don-vi/xac-thuc-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: xacThucOtpRequest
    },
      );
    }
  export const dangKyDonVi = (
    dangKyDonViRequest: DangKyDonViRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/don-vi/dang-ky`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dangKyDonViRequest
    },
      );
    }
  export const layDanhSach29 = (
    params?: LayDanhSach29Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseDonViResponse>(
      {url: `/api/don-vi`, method: 'GET',
        params
    },
      );
    }
  export const checkDomain = (
    params: CheckDomainParams,
 ) => {
      return customAxiosInstance<ApiResponseCheckDomainResponse>(
      {url: `/api/don-vi/check-domain`, method: 'GET',
        params
    },
      );
    }
  export type LayTheoId21Result = NonNullable<Awaited<ReturnType<typeof layTheoId21>>>
export type CapNhatThongTinResult = NonNullable<Awaited<ReturnType<typeof capNhatThongTin>>>
export type XoaMem21Result = NonNullable<Awaited<ReturnType<typeof xoaMem21>>>
export type CapNhatTrangThai13Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai13>>>
export type GiaHanHopDongResult = NonNullable<Awaited<ReturnType<typeof giaHanHopDong>>>
export type XacThucOtpResult = NonNullable<Awaited<ReturnType<typeof xacThucOtp>>>
export type DangKyDonViResult = NonNullable<Awaited<ReturnType<typeof dangKyDonVi>>>
export type LayDanhSach29Result = NonNullable<Awaited<ReturnType<typeof layDanhSach29>>>
export type CheckDomainResult = NonNullable<Awaited<ReturnType<typeof checkDomain>>>
