/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseActiveAllocationResponse,
  ApiResponsePageResponsePhieuThuHoiTaiSanResponse,
  ApiResponsePhieuThuHoiTaiSanResponse,
  ApiResponseString,
  LayAllocationsCuaNhanVienParams,
  LayDanhSach7Params,
  PhieuThuHoiTaiSanRequest,
  TuChoiPheDuyetParams
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId7 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponsePhieuThuHoiTaiSanResponse>(
      {url: `/api/phieu-thu-hoi/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat7 = (
    id: number,
    phieuThuHoiTaiSanRequest: PhieuThuHoiTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuThuHoiTaiSanResponse>(
      {url: `/api/phieu-thu-hoi/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: phieuThuHoiTaiSanRequest
    },
      );
    }
  export const xoaMem7 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-thu-hoi/${id}`, method: 'DELETE'
    },
      );
    }
  export const yeuCauPheDuyet = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-thu-hoi/${id}/yeu-cau-phe-duyet`, method: 'PUT'
    },
      );
    }
  export const tuChoiPheDuyet = (
    id: number,
    params: TuChoiPheDuyetParams,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-thu-hoi/${id}/tu-choi`, method: 'PUT',
        params
    },
      );
    }
  export const pheDuyet = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-thu-hoi/${id}/phe-duyet`, method: 'PUT'
    },
      );
    }
  export const hoanThanh = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-thu-hoi/${id}/hoan-thanh`, method: 'PUT'
    },
      );
    }
  export const layDanhSach7 = (
    params?: LayDanhSach7Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponsePhieuThuHoiTaiSanResponse>(
      {url: `/api/phieu-thu-hoi`, method: 'GET',
        params
    },
      );
    }
  export const themMoi7 = (
    phieuThuHoiTaiSanRequest: PhieuThuHoiTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuThuHoiTaiSanResponse>(
      {url: `/api/phieu-thu-hoi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: phieuThuHoiTaiSanRequest
    },
      );
    }
  export const layAllocationsCuaNhanVien = (
    params: LayAllocationsCuaNhanVienParams,
 ) => {
      return customAxiosInstance<ApiResponseActiveAllocationResponse>(
      {url: `/api/phieu-thu-hoi/active-allocations`, method: 'GET',
        params
    },
      );
    }
  export type LayTheoId7Result = NonNullable<Awaited<ReturnType<typeof layTheoId7>>>
export type CapNhat7Result = NonNullable<Awaited<ReturnType<typeof capNhat7>>>
export type XoaMem7Result = NonNullable<Awaited<ReturnType<typeof xoaMem7>>>
export type YeuCauPheDuyetResult = NonNullable<Awaited<ReturnType<typeof yeuCauPheDuyet>>>
export type TuChoiPheDuyetResult = NonNullable<Awaited<ReturnType<typeof tuChoiPheDuyet>>>
export type PheDuyetResult = NonNullable<Awaited<ReturnType<typeof pheDuyet>>>
export type HoanThanhResult = NonNullable<Awaited<ReturnType<typeof hoanThanh>>>
export type LayDanhSach7Result = NonNullable<Awaited<ReturnType<typeof layDanhSach7>>>
export type ThemMoi7Result = NonNullable<Awaited<ReturnType<typeof themMoi7>>>
export type LayAllocationsCuaNhanVienResult = NonNullable<Awaited<ReturnType<typeof layAllocationsCuaNhanVien>>>
