/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseLapRapLinhKienResponse,
  ApiResponsePageResponseLapRapLinhKienResponse,
  ApiResponseString,
  LapRapLinhKienRequest,
  LapRapLinhKienResponse,
  LayDanhSach18Params
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const capNhatThaoDo = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/lap-rap/${id}/thao-do`, method: 'PUT'
    },
      );
    }
  export const layDanhSach18 = (
    params?: LayDanhSach18Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseLapRapLinhKienResponse>(
      {url: `/api/lap-rap`, method: 'GET',
        params
    },
      );
    }
  export const themMoi18 = (
    lapRapLinhKienRequest: LapRapLinhKienRequest,
 ) => {
      return customAxiosInstance<LapRapLinhKienResponse | ApiResponseLapRapLinhKienResponse>(
      {url: `/api/lap-rap`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: lapRapLinhKienRequest
    },
      );
    }
  export type CapNhatThaoDoResult = NonNullable<Awaited<ReturnType<typeof capNhatThaoDo>>>
export type LayDanhSach18Result = NonNullable<Awaited<ReturnType<typeof layDanhSach18>>>
export type ThemMoi18Result = NonNullable<Awaited<ReturnType<typeof themMoi18>>>
