/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseDanhSachThietBiPhanCungResponse,
  ApiResponseListSelectOption,
  ApiResponsePageResponseDanhSachThietBiPhanCungResponse,
  ApiResponseString,
  DanhSachThietBiPhanCungRequest,
  LayDanhSach3Params,
  TrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId3 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseDanhSachThietBiPhanCungResponse>(
      {url: `/api/thiet-bi-phan-cung/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat3 = (
    id: number,
    danhSachThietBiPhanCungRequest: DanhSachThietBiPhanCungRequest,
 ) => {
      return customAxiosInstance<ApiResponseDanhSachThietBiPhanCungResponse>(
      {url: `/api/thiet-bi-phan-cung/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: danhSachThietBiPhanCungRequest
    },
      );
    }
  export const xoaMem3 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/thiet-bi-phan-cung/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai3 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/thiet-bi-phan-cung/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach3 = (
    params?: LayDanhSach3Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseDanhSachThietBiPhanCungResponse>(
      {url: `/api/thiet-bi-phan-cung`, method: 'GET',
        params
    },
      );
    }
  export const themMoi3 = (
    danhSachThietBiPhanCungRequest: DanhSachThietBiPhanCungRequest,
 ) => {
      return customAxiosInstance<ApiResponseDanhSachThietBiPhanCungResponse>(
      {url: `/api/thiet-bi-phan-cung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: danhSachThietBiPhanCungRequest
    },
      );
    }
  export const laySelectOptions1 = (

 ) => {
      return customAxiosInstance<ApiResponseListSelectOption>(
      {url: `/api/thiet-bi-phan-cung/select-options`, method: 'GET'
    },
      );
    }
  export type LayTheoId3Result = NonNullable<Awaited<ReturnType<typeof layTheoId3>>>
export type CapNhat3Result = NonNullable<Awaited<ReturnType<typeof capNhat3>>>
export type XoaMem3Result = NonNullable<Awaited<ReturnType<typeof xoaMem3>>>
export type CapNhatTrangThai3Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai3>>>
export type LayDanhSach3Result = NonNullable<Awaited<ReturnType<typeof layDanhSach3>>>
export type ThemMoi3Result = NonNullable<Awaited<ReturnType<typeof themMoi3>>>
export type LaySelectOptions1Result = NonNullable<Awaited<ReturnType<typeof laySelectOptions1>>>
