/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseDotKiemKeResponse,
  ApiResponsePageResponseDotKiemKeResponse,
  ApiResponseString,
  DotKiemKeRequest,
  LayDanhSach21Params
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId20 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseDotKiemKeResponse>(
      {url: `/api/dot-kiem-ke/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat20 = (
    id: number,
    dotKiemKeRequest: DotKiemKeRequest,
 ) => {
      return customAxiosInstance<ApiResponseDotKiemKeResponse>(
      {url: `/api/dot-kiem-ke/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: dotKiemKeRequest
    },
      );
    }
  export const xoaMem20 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/dot-kiem-ke/${id}`, method: 'DELETE'
    },
      );
    }
  export const yeuCauPheDuyet6 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/dot-kiem-ke/${id}/yeu-cau-phe-duyet`, method: 'PUT'
    },
      );
    }
  export const pheDuyet6 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/dot-kiem-ke/${id}/phe-duyet`, method: 'PUT'
    },
      );
    }
  export const layDanhSach21 = (
    params?: LayDanhSach21Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseDotKiemKeResponse>(
      {url: `/api/dot-kiem-ke`, method: 'GET',
        params
    },
      );
    }
  export const themMoi21 = (
    dotKiemKeRequest: DotKiemKeRequest,
 ) => {
      return customAxiosInstance<ApiResponseDotKiemKeResponse>(
      {url: `/api/dot-kiem-ke`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dotKiemKeRequest
    },
      );
    }
  export type LayTheoId20Result = NonNullable<Awaited<ReturnType<typeof layTheoId20>>>
export type CapNhat20Result = NonNullable<Awaited<ReturnType<typeof capNhat20>>>
export type XoaMem20Result = NonNullable<Awaited<ReturnType<typeof xoaMem20>>>
export type YeuCauPheDuyet6Result = NonNullable<Awaited<ReturnType<typeof yeuCauPheDuyet6>>>
export type PheDuyet6Result = NonNullable<Awaited<ReturnType<typeof pheDuyet6>>>
export type LayDanhSach21Result = NonNullable<Awaited<ReturnType<typeof layDanhSach21>>>
export type ThemMoi21Result = NonNullable<Awaited<ReturnType<typeof themMoi21>>>
