/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponsePageResponseViTriResponse,
  ApiResponseString,
  ApiResponseViTriResponse,
  LayDanhSachParams,
  TrangThaiRequest,
  ViTriRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseViTriResponse>(
      {url: `/api/vi-tri/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat = (
    id: number,
    viTriRequest: ViTriRequest,
 ) => {
      return customAxiosInstance<ApiResponseViTriResponse>(
      {url: `/api/vi-tri/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: viTriRequest
    },
      );
    }
  export const xoaMem = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/vi-tri/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/vi-tri/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach = (
    params?: LayDanhSachParams,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseViTriResponse>(
      {url: `/api/vi-tri`, method: 'GET',
        params
    },
      );
    }
  export const themMoi = (
    viTriRequest: ViTriRequest,
 ) => {
      return customAxiosInstance<ApiResponseViTriResponse>(
      {url: `/api/vi-tri`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: viTriRequest
    },
      );
    }
  export type LayTheoIdResult = NonNullable<Awaited<ReturnType<typeof layTheoId>>>
export type CapNhatResult = NonNullable<Awaited<ReturnType<typeof capNhat>>>
export type XoaMemResult = NonNullable<Awaited<ReturnType<typeof xoaMem>>>
export type CapNhatTrangThaiResult = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai>>>
export type LayDanhSachResult = NonNullable<Awaited<ReturnType<typeof layDanhSach>>>
export type ThemMoiResult = NonNullable<Awaited<ReturnType<typeof themMoi>>>
