/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseDanhMucTaiSanResponse,
  ApiResponseListSelectOption,
  ApiResponsePageResponseDanhMucTaiSanResponse,
  ApiResponseString,
  DanhMucTaiSanRequest,
  LayDanhSach24Params,
  TrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId24 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseDanhMucTaiSanResponse>(
      {url: `/api/danh-muc-tai-san/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat23 = (
    id: number,
    danhMucTaiSanRequest: DanhMucTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponseDanhMucTaiSanResponse>(
      {url: `/api/danh-muc-tai-san/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: danhMucTaiSanRequest
    },
      );
    }
  export const xoaMem24 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/danh-muc-tai-san/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai15 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/danh-muc-tai-san/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach24 = (
    params?: LayDanhSach24Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseDanhMucTaiSanResponse>(
      {url: `/api/danh-muc-tai-san`, method: 'GET',
        params
    },
      );
    }
  export const themMoi24 = (
    danhMucTaiSanRequest: DanhMucTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponseDanhMucTaiSanResponse>(
      {url: `/api/danh-muc-tai-san`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: danhMucTaiSanRequest
    },
      );
    }
  export const laySelectOptions9 = (

 ) => {
      return customAxiosInstance<ApiResponseListSelectOption>(
      {url: `/api/danh-muc-tai-san/select-options`, method: 'GET'
    },
      );
    }
  export type LayTheoId24Result = NonNullable<Awaited<ReturnType<typeof layTheoId24>>>
export type CapNhat23Result = NonNullable<Awaited<ReturnType<typeof capNhat23>>>
export type XoaMem24Result = NonNullable<Awaited<ReturnType<typeof xoaMem24>>>
export type CapNhatTrangThai15Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai15>>>
export type LayDanhSach24Result = NonNullable<Awaited<ReturnType<typeof layDanhSach24>>>
export type ThemMoi24Result = NonNullable<Awaited<ReturnType<typeof themMoi24>>>
export type LaySelectOptions9Result = NonNullable<Awaited<ReturnType<typeof laySelectOptions9>>>
