/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseString
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const nhacNhoChungTu = (

 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/thong-bao/nhac-nho-chung-tu`, method: 'GET'
    },
      );
    }
  export const canhBaoHetHan = (

 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/thong-bao/canh-bao-het-han`, method: 'GET'
    },
      );
    }
  export type NhacNhoChungTuResult = NonNullable<Awaited<ReturnType<typeof nhacNhoChungTu>>>
export type CanhBaoHetHanResult = NonNullable<Awaited<ReturnType<typeof canhBaoHetHan>>>
