/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseString,
  NhacNhoKiemKeCuTheParams
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const nhacNhoKiemKe = (

 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/thong-bao/nhac-nho-kiem-ke`, method: 'GET'
    },
      );
    }
  export const nhacNhoKiemKeCuThe = (
    params: NhacNhoKiemKeCuTheParams,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/thong-bao/nhac-nho-kiem-ke-cu-the`, method: 'GET',
        params
    },
      );
    }
  export const nhacNhoChungTu = (

 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/thong-bao/nhac-nho-chung-tu`, method: 'GET'
    },
      );
    }
  export const canhBaoHetHan = (

 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/thong-bao/canh-bao-het-han`, method: 'GET'
    },
      );
    }
  export type NhacNhoKiemKeResult = NonNullable<Awaited<ReturnType<typeof nhacNhoKiemKe>>>
export type NhacNhoKiemKeCuTheResult = NonNullable<Awaited<ReturnType<typeof nhacNhoKiemKeCuThe>>>
export type NhacNhoChungTuResult = NonNullable<Awaited<ReturnType<typeof nhacNhoChungTu>>>
export type CanhBaoHetHanResult = NonNullable<Awaited<ReturnType<typeof canhBaoHetHan>>>
