/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseListString
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const getMyPermissions = (

 ) => {
      return customAxiosInstance<ApiResponseListString>(
      {url: `/api/iam/my-permissions`, method: 'GET'
    },
      );
    }
  export type GetMyPermissionsResult = NonNullable<Awaited<ReturnType<typeof getMyPermissions>>>
