/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseLinhKienPhanCungResponse,
  ApiResponseListSelectOption,
  ApiResponsePageResponseLinhKienPhanCungResponse,
  ApiResponseString,
  LayDanhSach17Params,
  LaySelectOptions8Params,
  LinhKienPhanCungRequest,
  TrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId17 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseLinhKienPhanCungResponse>(
      {url: `/api/linh-kien-phan-cung/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat17 = (
    id: number,
    linhKienPhanCungRequest: LinhKienPhanCungRequest,
 ) => {
      return customAxiosInstance<ApiResponseLinhKienPhanCungResponse>(
      {url: `/api/linh-kien-phan-cung/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: linhKienPhanCungRequest
    },
      );
    }
  export const xoaMem17 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/linh-kien-phan-cung/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai11 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/linh-kien-phan-cung/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach17 = (
    params?: LayDanhSach17Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseLinhKienPhanCungResponse>(
      {url: `/api/linh-kien-phan-cung`, method: 'GET',
        params
    },
      );
    }
  export const themMoi17 = (
    linhKienPhanCungRequest: LinhKienPhanCungRequest,
 ) => {
      return customAxiosInstance<ApiResponseLinhKienPhanCungResponse>(
      {url: `/api/linh-kien-phan-cung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linhKienPhanCungRequest
    },
      );
    }
  export const laySelectOptions8 = (
    params?: LaySelectOptions8Params,
 ) => {
      return customAxiosInstance<ApiResponseListSelectOption>(
      {url: `/api/linh-kien-phan-cung/select-options`, method: 'GET',
        params
    },
      );
    }
  export type LayTheoId17Result = NonNullable<Awaited<ReturnType<typeof layTheoId17>>>
export type CapNhat17Result = NonNullable<Awaited<ReturnType<typeof capNhat17>>>
export type XoaMem17Result = NonNullable<Awaited<ReturnType<typeof xoaMem17>>>
export type CapNhatTrangThai11Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai11>>>
export type LayDanhSach17Result = NonNullable<Awaited<ReturnType<typeof layDanhSach17>>>
export type ThemMoi17Result = NonNullable<Awaited<ReturnType<typeof themMoi17>>>
export type LaySelectOptions8Result = NonNullable<Awaited<ReturnType<typeof laySelectOptions8>>>
