/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseListString,
  ApiResponseString,
  DownloadParams,
  UploadParams
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const upload = (
    params: UploadParams,
 ) => {
      return customAxiosInstance<ApiResponseListString>(
      {url: `/api/files/upload`, method: 'POST',
        params
    },
      );
    }
  export const download = (
    params: DownloadParams,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/files/download`, method: 'GET',
        params
    },
      );
    }
  export type UploadResult = NonNullable<Awaited<ReturnType<typeof upload>>>
export type DownloadResult = NonNullable<Awaited<ReturnType<typeof download>>>
