/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseListSelectOption,
  ApiResponsePageResponseTaiSanPhanMemResponse,
  ApiResponseString,
  ApiResponseTaiSanPhanMemResponse,
  LayDanhSach4Params,
  LaySelectOptions2Params,
  TaiSanPhanMemRequest,
  TrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId4 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseTaiSanPhanMemResponse>(
      {url: `/api/tai-san-phan-mem/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat4 = (
    id: number,
    taiSanPhanMemRequest: TaiSanPhanMemRequest,
 ) => {
      return customAxiosInstance<ApiResponseTaiSanPhanMemResponse>(
      {url: `/api/tai-san-phan-mem/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: taiSanPhanMemRequest
    },
      );
    }
  export const xoaMem4 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/tai-san-phan-mem/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai4 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/tai-san-phan-mem/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach4 = (
    params?: LayDanhSach4Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseTaiSanPhanMemResponse>(
      {url: `/api/tai-san-phan-mem`, method: 'GET',
        params
    },
      );
    }
  export const themMoi4 = (
    taiSanPhanMemRequest: TaiSanPhanMemRequest,
 ) => {
      return customAxiosInstance<ApiResponseTaiSanPhanMemResponse>(
      {url: `/api/tai-san-phan-mem`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taiSanPhanMemRequest
    },
      );
    }
  export const laySelectOptions2 = (
    params?: LaySelectOptions2Params,
 ) => {
      return customAxiosInstance<ApiResponseListSelectOption>(
      {url: `/api/tai-san-phan-mem/select-options`, method: 'GET',
        params
    },
      );
    }
  export type LayTheoId4Result = NonNullable<Awaited<ReturnType<typeof layTheoId4>>>
export type CapNhat4Result = NonNullable<Awaited<ReturnType<typeof capNhat4>>>
export type XoaMem4Result = NonNullable<Awaited<ReturnType<typeof xoaMem4>>>
export type CapNhatTrangThai4Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai4>>>
export type LayDanhSach4Result = NonNullable<Awaited<ReturnType<typeof layDanhSach4>>>
export type ThemMoi4Result = NonNullable<Awaited<ReturnType<typeof themMoi4>>>
export type LaySelectOptions2Result = NonNullable<Awaited<ReturnType<typeof laySelectOptions2>>>
