/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponsePageResponsePhieuThanhLyTaiSanResponse,
  ApiResponsePhieuThanhLyTaiSanResponse,
  ApiResponseString,
  LayDanhSach8Params,
  PhieuThanhLyTaiSanRequest,
  TuChoiPheDuyet1Params
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId8 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponsePhieuThanhLyTaiSanResponse>(
      {url: `/api/phieu-thanh-ly/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat8 = (
    id: number,
    phieuThanhLyTaiSanRequest: PhieuThanhLyTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuThanhLyTaiSanResponse>(
      {url: `/api/phieu-thanh-ly/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: phieuThanhLyTaiSanRequest
    },
      );
    }
  export const xoaMem8 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-thanh-ly/${id}`, method: 'DELETE'
    },
      );
    }
  export const yeuCauPheDuyet1 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-thanh-ly/${id}/yeu-cau-phe-duyet`, method: 'PUT'
    },
      );
    }
  export const tuChoiPheDuyet1 = (
    id: number,
    params: TuChoiPheDuyet1Params,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-thanh-ly/${id}/tu-choi`, method: 'PUT',
        params
    },
      );
    }
  export const pheDuyet1 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-thanh-ly/${id}/phe-duyet`, method: 'PUT'
    },
      );
    }
  export const hoanThanh1 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/phieu-thanh-ly/${id}/hoan-thanh`, method: 'PUT'
    },
      );
    }
  export const layDanhSach8 = (
    params?: LayDanhSach8Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponsePhieuThanhLyTaiSanResponse>(
      {url: `/api/phieu-thanh-ly`, method: 'GET',
        params
    },
      );
    }
  export const themMoi8 = (
    phieuThanhLyTaiSanRequest: PhieuThanhLyTaiSanRequest,
 ) => {
      return customAxiosInstance<ApiResponsePhieuThanhLyTaiSanResponse>(
      {url: `/api/phieu-thanh-ly`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: phieuThanhLyTaiSanRequest
    },
      );
    }
  export type LayTheoId8Result = NonNullable<Awaited<ReturnType<typeof layTheoId8>>>
export type CapNhat8Result = NonNullable<Awaited<ReturnType<typeof capNhat8>>>
export type XoaMem8Result = NonNullable<Awaited<ReturnType<typeof xoaMem8>>>
export type YeuCauPheDuyet1Result = NonNullable<Awaited<ReturnType<typeof yeuCauPheDuyet1>>>
export type TuChoiPheDuyet1Result = NonNullable<Awaited<ReturnType<typeof tuChoiPheDuyet1>>>
export type PheDuyet1Result = NonNullable<Awaited<ReturnType<typeof pheDuyet1>>>
export type HoanThanh1Result = NonNullable<Awaited<ReturnType<typeof hoanThanh1>>>
export type LayDanhSach8Result = NonNullable<Awaited<ReturnType<typeof layDanhSach8>>>
export type ThemMoi8Result = NonNullable<Awaited<ReturnType<typeof themMoi8>>>
