/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * IT Asset Management API
 * Tài liệu API Hệ thống quản lý tài sản CNTT
 * OpenAPI spec version: 1.0
 */
import type {
  ApiResponseDanhSachThietBiPhanMemResponse,
  ApiResponseListSelectOption,
  ApiResponsePageResponseDanhSachThietBiPhanMemResponse,
  ApiResponseString,
  DanhSachThietBiPhanMemRequest,
  LayDanhSach2Params,
  LaySelectOptionsParams,
  TrangThaiRequest
} from '../../models';

import { customAxiosInstance } from '../../../api/axiosInstance';



  export const layTheoId2 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseDanhSachThietBiPhanMemResponse>(
      {url: `/api/thiet-bi-phan-mem/${id}`, method: 'GET'
    },
      );
    }
  export const capNhat2 = (
    id: number,
    danhSachThietBiPhanMemRequest: DanhSachThietBiPhanMemRequest,
 ) => {
      return customAxiosInstance<ApiResponseDanhSachThietBiPhanMemResponse>(
      {url: `/api/thiet-bi-phan-mem/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: danhSachThietBiPhanMemRequest
    },
      );
    }
  export const xoaMem2 = (
    id: number,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/thiet-bi-phan-mem/${id}`, method: 'DELETE'
    },
      );
    }
  export const capNhatTrangThai2 = (
    id: number,
    trangThaiRequest: TrangThaiRequest,
 ) => {
      return customAxiosInstance<ApiResponseString>(
      {url: `/api/thiet-bi-phan-mem/${id}/trang-thai`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: trangThaiRequest
    },
      );
    }
  export const layDanhSach2 = (
    params?: LayDanhSach2Params,
 ) => {
      return customAxiosInstance<ApiResponsePageResponseDanhSachThietBiPhanMemResponse>(
      {url: `/api/thiet-bi-phan-mem`, method: 'GET',
        params
    },
      );
    }
  export const themMoi2 = (
    danhSachThietBiPhanMemRequest: DanhSachThietBiPhanMemRequest,
 ) => {
      return customAxiosInstance<ApiResponseDanhSachThietBiPhanMemResponse>(
      {url: `/api/thiet-bi-phan-mem`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: danhSachThietBiPhanMemRequest
    },
      );
    }
  export const laySelectOptions = (
    params?: LaySelectOptionsParams,
 ) => {
      return customAxiosInstance<ApiResponseListSelectOption>(
      {url: `/api/thiet-bi-phan-mem/select-options`, method: 'GET',
        params
    },
      );
    }
  export type LayTheoId2Result = NonNullable<Awaited<ReturnType<typeof layTheoId2>>>
export type CapNhat2Result = NonNullable<Awaited<ReturnType<typeof capNhat2>>>
export type XoaMem2Result = NonNullable<Awaited<ReturnType<typeof xoaMem2>>>
export type CapNhatTrangThai2Result = NonNullable<Awaited<ReturnType<typeof capNhatTrangThai2>>>
export type LayDanhSach2Result = NonNullable<Awaited<ReturnType<typeof layDanhSach2>>>
export type ThemMoi2Result = NonNullable<Awaited<ReturnType<typeof themMoi2>>>
export type LaySelectOptionsResult = NonNullable<Awaited<ReturnType<typeof laySelectOptions>>>
